AUTO = 'auto'
BOULDER = 'Boulder'
BOULDERS = 'Boulders'
CROSSING = 'Crossing'
CROSSINGS = 'crossings'
FACE = 'Face'
HIGH = 'High'
LOW = 'Low'
POINTS = 'Points'
POSITION = 'position'
REACH = 'Reach'
TELEOP = 'teleop'
TOWER = 'tower'

ADJUST_POINTS = 'adjustPoints'

AUTO_BOULDER_POINTS = AUTO + BOULDER + POINTS
AUTO_BOULDERS_HIGH = AUTO + BOULDERS + HIGH
AUTO_BOULDERS_LOW = AUTO + BOULDERS + LOW
AUTO_CROSSING_POINTS = AUTO + CROSSING + POINTS
AUTO_POINTS = AUTO + POINTS
AUTO_REACH_POINTS = AUTO + REACH + POINTS

BREACH_POINTS = 'breach' + POINTS
CAPTURE_POINTS = 'capture' + POINTS

FOUL_COUNT = 'foulCount'
TECH_FOUL_COUNT = 'techFoulCount'
FOUL_POINTS = 'foul' + POINTS

POSITION1 = POSITION + '1'
POSITION1_CROSSINGS = POSITION1 + CROSSINGS
POSITION2 = POSITION + '2'
POSITION2_CROSSINGS = POSITION2 + CROSSINGS
POSITION3 = POSITION + '3'
POSITION3_CROSSINGS = POSITION3 + CROSSINGS
POSITION4 = POSITION + '4'
POSITION4_CROSSINGS = POSITION4 + CROSSINGS
POSITION5 = POSITION + '5'
POSITION5_CROSSINGS = POSITION5 + CROSSINGS

ROBOT1_AUTO = 'robot1Auto'
ROBOT2_AUTO = 'robot2Auto'
ROBOT3_AUTO = 'robot3Auto'

TELEOP_BOULDER_POINTS = TELEOP + BOULDER + POINTS
TELEOP_BOULDERS_HIGH = TELEOP + BOULDERS + HIGH
TELEOP_BOULDERS_LOW = TELEOP + BOULDERS + LOW
TELEOP_CHALLENGE_POINTS = TELEOP + 'Challenge' + POINTS
TELEOP_CROSSING_POINTS = TELEOP + CROSSING + POINTS
TELEOP_DEFENSES_BREACHED = TELEOP + 'DefensesBreached'
TELEOP_SCALE_POINTS = TELEOP + 'Scale' + POINTS
TELEOP_TOWER_CAPTURED = TELEOP + 'Tower' + 'Captured'
TELEOP_POINTS = TELEOP + POINTS

TOWER_END_STRENGTH = TOWER + 'EndStrength'
TOWER_FACE_A = TOWER + FACE + 'A'
TOWER_FACE_B = TOWER + FACE + 'B'
TOWER_FACE_C = TOWER + FACE + 'C'

TOTAL_POINTS = 'total' + POINTS

A_CHEVALDEFFRISE = 'A_ChevalDeFrise'
A_PORTCULLIS = 'A_Portcullis'
B_RAMPARTS = 'B_Ramparts'
B_MOAT = 'B_Moat'
C_SALLYPORT = 'C_SallyPort'
C_DRAWBRIDGE = 'C_Drawbridge'
D_ROCKWALL = 'D_RockWall'
D_ROUGHTERRAIN = 'D_RoughTerrain'


